name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build action
      run: npm run build
    
    - name: Run tests
      run: npm test
    
    - name: Check if dist/ is up to date
      run: |
        if [ -n "$(git status --porcelain dist/)" ]; then
          echo "dist/ is not up to date. Please run 'npm run build' and commit the changes."
          exit 1
        fi
